# This is a basic workflow to help you get started with Actions

name: terraformpipeline

# Controls when the workflow will run
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform-job:
    runs-on: self-hosted
    steps:
    - name: Print Message
      run: echo "Hello from Self Hosted Runner"

